name: "DevSecOps CI CD Pipeline"

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SonarQube Code Analysis
        run: |
          docker run --rm \
            --network lab_work_back-net \
            -v ${{ github.workspace }}:/usr/src \
            sonarsource/sonar-scanner-cli \
            -Dsonar.host.url=http://sonarqube:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.projectKey=Lab-Work-DevSecOps \
            -Dsonar.projectName="Lab Work DevSecOps" \
            -Dsonar.sources=. \
            -Dsonar.scanner.skipNodeProvisioning=true

      - name: Log in to Nexus Docker Registry
        run: |
          echo "${{ secrets.NEXUS_PASSWORD }}" | docker login http://nexus.sverahtin.com -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t nexus.sverahtin.com/lab-work-app:${{ github.sha }} -t nexus.sverahtin.com/lab-work-app:latest nginx

      - name: Push Image to Nexus
        run: |
          docker push nexus.sverahtin.com/lab-work-app:${{ github.sha }}
          docker push nexus.sverahtin.com/lab-work-app:latest
